# Generated by Django 4.1.4 on 2022-12-27 06:32

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='stu_cls_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], default=1, max_length=20, null=True)),
                ('mothly_fee', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fathername', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=15)),
                ('fee_status', models.CharField(blank=True, choices=[('1', '1st month'), ('2', '2nd month'), ('3', '3rd month'), ('4', '4th month'), ('5', '5th month'), ('6', '6th month'), ('7', '7th month'), ('8', '8th month'), ('9', '9th month'), ('10', '10th month'), ('11', '11th month'), ('12', '12th month')], max_length=20, null=True)),
                ('fee', models.BigIntegerField(default=200)),
                ('gen_cat', models.BooleanField(default=False)),
                ('admitted_on', models.DateTimeField(auto_now=True)),
                ('roll', models.BigIntegerField(null=True)),
                ('fee_received_by', models.CharField(max_length=30, null=True)),
                ('clas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.stu_cls_model')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
