# Generated by Django 4.1.4 on 2023-01-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_clas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fee_status',
            field=models.CharField(choices=[('1', '1st month'), ('2', '2nd month'), ('3', '3rd month'), ('4', '4th month'), ('5', '5th month'), ('6', '6th month'), ('7', '7th month'), ('8', '8th month'), ('9', '9th month'), ('10', '10th month'), ('11', '11th month'), ('12', '12th month')], default=1, max_length=20),
        ),
    ]
