# Generated by Django 4.1.4 on 2023-01-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_attendance_is_present_alter_attendance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
