# Generated by Django 4.1.4 on 2023-01-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_attendance_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attdate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
