# Generated by Django 4.1.4 on 2023-01-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_attendance_date_attendance_attdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_present_today',
            field=models.CharField(blank=True, default='Absent', max_length=15),
        ),
    ]
