# Generated by Django 4.1.4 on 2023-01-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_student_is_present_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_present_today',
            field=models.CharField(blank=True, default='absent', max_length=15),
        ),
    ]
