# Generated by Django 4.1.4 on 2023-01-16 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_notificatiions_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificatiions',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
