# Generated by Django 4.1.4 on 2023-01-16 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_notificatiions_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notificatiions',
            new_name='notifications',
        ),
    ]
