# Generated by Django 4.1.4 on 2023-01-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_rename_notificatiions_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='users',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
