# Generated by Django 4.1.4 on 2023-01-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_notifications_is_read'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notifications',
            new_name='notification',
        ),
    ]
