# Generated by Django 4.1.4 on 2023-01-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_alter_notification_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='users',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
